services:
  app:
    container_name: app
    build:
      context: .
      target: app
      args:
        DEV_MODE: 1
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=resender}
      DATABASE_HOST: database
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      MESSENGER_TRANSPORT_DSN: sqs://elasticmq:9324/default?sslmode=disable
    depends_on:
      - database
      - elasticmq
    volumes:
      - ./:/var/www/html:cached

  consumer:
    container_name: consumer
    build:
      context: .
      target: app
      args:
        DEV_MODE: 1
    environment:
      # To use xdebug, set XDEBUG_TRIGGER to PHPSTORM and restart the container (via compose of course)
      XDEBUG_TRIGGER: ${XDEBUG_TRIGGER:-}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=resender}
      DATABASE_HOST: database
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      MESSENGER_TRANSPORT_DSN: sqs://elasticmq:9324/default?sslmode=disable
      # Following AWS_* values works as workaround for SQS transport SDK.
      # If they are not set SDK tries to fetch metadata from EC2 instance and hangs for a while.
      # With these values set, it works without any delay.
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - database
      - elasticmq
    command: ["php", "bin/console", "messenger:consume", "async", "-vv"]
    volumes:
      - ./:/var/www/html:cached

  web-server:
    container_name: web-server
    build:
      context: .
      target: web
    depends_on:
      - app
    ports:
      - "8080:80"

  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-resender}
      POSTGRES_USER: ${POSTGRES_USER:-resender}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    ports:
      - "5432:5432"
    volumes:
      - $HOME/.postgres/data:/var/lib/postgresql/data

  elasticmq:
    container_name: elasticmq
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324" # SQS API
      - "9325:9325" # Web UI
    volumes:
      - ./docker/elasticmq/elasticmq.conf:/opt/elasticmq.conf