sonar.projectKey=resender

# --- optional properties ---

sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=var/analysis/coverage.xml
sonar.php.tests.reportPath=var/analysis/tests.xml
sonar.php.phpstan.reportPaths=var/analysis/phpstan.json
sonar.php.phpcs.reportPath=var/analysis/phpcs.json

sonar.login=sqp_17d941cc9cf4b00d27b1a4eecd3bbfcdd6ea6a03
sonar.host.url=https://sonarqube.wallmob.com

sonar.pullrequest.key=${env.GITHUB_PR_NUMBER}
sonar.pullrequest.branch=${env.GITHUB_HEAD_REF}
sonar.pullrequest.base=${env.GITHUB_BASE_REF}
#
#sonar.branch.name=test-sonarqube-branches