sonar.projectKey=LogParser

# --- optional properties ---

sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=output/analysis/coverage.xml
sonar.php.tests.reportPath=output/analysis/tests.xml
sonar.php.phpstan.reportPaths=output/analysis/phpstan.json
sonar.php.phpcs.reportPath=output/analysis/phpcs.json