sonar.projectKey=ReSender

# --- optional properties ---

sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=var/analysis/coverage.xml
sonar.php.tests.reportPath=var/analysis/tests.xml
sonar.php.phpstan.reportPaths=var/analysis/phpstan.json
sonar.php.phpcs.reportPath=var/analysis/phpcs.json