# An action which adds reviewers to the pull request when the pull request is opened.
# @link https://github.com/marketplace/actions/auto-assign-action
# @link https://github.com/kentaro-m/auto-assign-action

#name: 'Pull Request Auto Assign'
#on:
#    pull_request:
#        types: [opened, ready_for_review]
#jobs:
#    pr-auto-assign:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: kentaro-m/auto-assign-action@v1.2.0
#              with:
#                  configuration-path: '.github/actions/pr-auto-assign/pr-auto-assign-config.yaml'


name: PHP Composer

on:
    pull_request:
        types: [opened, ready_for_review, synchronize]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        env:
          GITHUB_PR_NUMBER: ${{github.event.number}}

        steps:
            - uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run analysis
              run: composer analysis:full

            - name: TEST
              run: echo $GITHUB_HEAD_REF; echo $GITHUB_BASE_REF; echo $GITHUB_PR_NUMBER

            - name: SonarCloud Scan
              run: '.github/scripts/run-analyzer.sh'


